"""Generated navigation: INDEX.md and manifest.json at the root of a knowledge base.

Indexes are rebuilt by this script, never by hand or by a language model, and they hold no
knowledge of their own. Output depends only on the cards (no timestamp, no "today"), so
``--check`` can tell whether a committed index is out of date. Overdue reviews are reported by
``teamkb validate``.
"""

from __future__ import annotations

import hashlib
import json
from collections import Counter

from .cards import CARD_TYPES, STATUSES, Card
from .config import KBConfig

INDEX_NAME = "INDEX.md"
MANIFEST_NAME = "manifest.json"


def content_hash(cards: list[Card]) -> str:
    digest = hashlib.sha256()
    for card in sorted(cards, key=lambda c: c.id):
        digest.update(card.id.encode())
        digest.update(b"\0")
        digest.update(card.raw.encode("utf-8"))
        digest.update(b"\0")
    return digest.hexdigest()[:12]


def latest_update(cards: list[Card]) -> str:
    dates = [d for d in (c.date("updated") for c in cards) if d]
    return max(dates).isoformat() if dates else ""


def _sort_key(card: Card) -> tuple[int, str]:
    order = list(CARD_TYPES)
    return (order.index(card.type) if card.type in order else len(order), card.id)


def render_index(config: KBConfig, cards: list[Card]) -> str:
    cards = sorted(cards, key=_sort_key)
    lines = [
        f"# {config.name} - index",
        "",
        "Generated by `teamkb index`. Do not edit: change the cards, then rebuild.",
        "",
        f"Cards: {len(cards)} | content {content_hash(cards)} | "
        f"latest update {latest_update(cards)}",
        "",
        "## Counts",
        "",
        "| Type | " + " | ".join(STATUSES) + " |",
        "|---|" + "---:|" * len(STATUSES),
    ]
    counts = Counter((c.type, c.status) for c in cards)
    for ctype in CARD_TYPES.values():
        row = [str(counts.get((ctype.name, s), 0)) for s in STATUSES]
        lines.append(f"| {ctype.label} | " + " | ".join(row) + " |")

    for ctype in CARD_TYPES.values():
        group = [c for c in cards if c.type == ctype.name]
        if not group:
            continue
        lines += [
            "",
            f"## {ctype.label}",
            "",
            "| ID | Title | Status | Classification | Review by |",
            "|---|---|---|---|---|",
        ]
        for c in group:
            link = f"cards/{ctype.folder}/{c.path.name}".replace(" ", "%20")
            review = c.date("review_by").isoformat() if c.date("review_by") else ""
            lines.append(
                f"| {c.id} | [{c.title}]({link}) | {c.status} | {c.classification} | {review} |"
            )
    return "\n".join(lines) + "\n"


def render_manifest(config: KBConfig, cards: list[Card]) -> str:
    data = {
        "name": config.name,
        "cards": len(cards),
        "by_status": dict(sorted(Counter(c.status for c in cards).items())),
        "by_type": dict(sorted(Counter(c.type for c in cards).items())),
        "content_hash": content_hash(cards),
        "latest_update": latest_update(cards),
        "generated_by": "teamkb index",
    }
    return json.dumps(data, indent=2) + "\n"


def build_index(config: KBConfig, cards: list[Card], check: bool = False) -> list[str]:
    """Write (or, with ``check``, compare) INDEX.md and manifest.json.

    Returns the names of files that were out of date.
    """
    outputs = {
        INDEX_NAME: render_index(config, cards),
        MANIFEST_NAME: render_manifest(config, cards),
    }
    stale = []
    for name, text in outputs.items():
        path = config.root / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(name)
            if not check:
                path.write_text(text, encoding="utf-8", newline="\n")
    return stale
